### ISSUE TITLE
Update all references to API docs to point to correct URL

### ISSUE THREAD

**Issue by JDRomano2** [RomanoLab/comptox_ai#36]
The correct URL for the REST API documentation is https://comptox.ai/api/help/. Anything else (e.g.,https://comptox.ai/api/index.html) will likely fail, and therefore all references to bad URLs should be identified and removed.

**Comment by lisavader** [comment]
Hi there,
The link you posted (https://comptox.ai/api/help/) isn't working anymore.
Where can I find the API documentation instead?
